---
title: "Project_Graphs"
output: html_document
date: "2024-01-09"
---

```{r}
library(car)
library(lubridate)
library(readr)
library(tidyverse)
library(tseries)

# Exploring Graphs & LM, ANOVA, GLM ------------------------------------------------------------
viol_crime <- c("HOMICIDE", "SEX ABUSE", "ROBBERY", "ASSAULT W/DANGEROUS WEAPON")


# START-REPORT
report_data <- rbind(dc.data2008, dc.data2009, dc.data2010, dc.data2011, dc.data2012, dc.data2013, dc.data2014, dc.data2015, dc.data2016, dc.data2017, dc.data2018, dc.data2019, dc.data2020, dc.data2021, dc.data2022, dc.data2023)%>%
               mutate(
                      VIOLENT_CRIME = ifelse(OFFENSE %in% viol_crime, 1, 0),
                      REPORT = ymd_hms(REPORT_DAT, tz = "America/New_York"),
                      START = ymd_hms(START_DATE, tz = "America/New_York")
               )%>%
               mutate(report_start_diff = as.numeric(difftime(REPORT, START, units = "hours")),
                      ) %>%
               filter(report_start_diff >= 0 & report_start_diff< 50000) #filter outliers
```

## R Markdown


```{r}
#Report vs Start Data
ggplot(
  report_data, 
  aes(x = REPORT, y= START, color= OFFENSE)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  labs(
    title = "Report vs Start Date",
    subtitle = "Influenced by Type of Crime",
       x = "Report Date",
       y = "Start Date"
    )

# Convert the categorical variable to a factor
report_data$OFFENSE <- factor(report_data$OFFENSE)
# Perform ANOVA
anova_result <- aov(report_start_diff ~ OFFENSE, data = report_data)
# Print ANOVA results
summary(anova_result)

#GLM Plot
report_data %>%
  ggplot(aes(x = report_start_diff, y = VIOLENT_CRIME)) +
  geom_point() +
  geom_smooth(method = "glm", method.args = list(family = "binomial"), se = FALSE) +
  labs(
    title = "Nonviolent and Violent Crime",
    subtitle =  "Difference Between Report and Start Date (hours) ",
    xlab = " Report Date - Start Date  ",
    ylab = "Violent Crime"
  )
glm_model <- glm(VIOLENT_CRIME ~ report_start_diff, data= report_data)
summary(glm_model)

print(prop.table(table(report_data$OFFENSE)) * 100)
print(prop.table(table(report_data$VIOLENT_CRIME)) * 100 )#Proportions of Non vs Violent Crime are not equivalent Nonviolent = 84.16% & Violent =15.84%

averages <- report_data %>%
  group_by(VIOLENT_CRIME) %>%
  summarise(mean_hours = mean(report_start_diff, na.rm = TRUE),
            median_hours = median(report_start_diff, na.rm = TRUE),
            min_hours = min(report_start_diff, na.rm = TRUE),
            max_hours = max(report_start_diff, na.rm = TRUE))
averages
```





```{r}

# MAP ---------------------------------------------------------------------
library(usmap)
library(plotly)
library(leaflet)
station.locations <- read.csv("https://opendata.arcgis.com/api/v3/datasets/05d048a0aa4845c6a0912f3a9f216992_6/downloads/data?format=csv&spatialRefId=4326&where=1%3D1", stringsAsFactors = FALSE)


# for loading our data
library(raster)
library(readr)
library(readxl)
library(sf)

# for datasets
library(maps)
library(spData)

# for plotting
library(tmap)
library(usmap)


tmap_mode("view")
#Load ward data
ward <- read_sf("Wards_from_2022.shp")

#Map 
dc_wards <- tm_shape(ward)+
  tm_polygons(col= "white", lwd= 3)+
  tm_layout(title = "Crimes Near EMS Locations", title.position = c("TOP", "center"))

  

  
#Violent Crime- Points

viol_sfplot<-report_data%>%
    st_as_sf(
      coords = c("LONGITUDE", "LATITUDE")
    )

viol_map <- tm_shape(viol_sfplot)+ 
  tm_dots(
    size= .005, col= "VIOLENT_CRIME", 
    pal = c("blue", "red"),
    breaks= c(0, 1, 1)
    )

#EMS- Points
ems_sfplot <- station.locations %>% 
  st_as_sf(
    coords = c("LONGITUDE", "LATITUDE")
  )

ems_map <- tm_shape(ems_sfplot)+
            tm_dots(size= .05, col = 'green')

#Combine

add_maps <-  dc_wards + viol_map + ems_map  
add_maps

tmap_arrange(dc_wards + viol_map + ems_map)




```





